### ISSUE TITLE
How to change text color ?

### ISSUE THREAD

**Issue by vuquangtam** [TobiasZawada/texfrag#19]
Hi, I'm using dark color mode, so i want my text color to white. How can i change text color ?

**Comment by TobiasZawada** [comment]
The color (foreground and background) of equations should automatically be adapted to the theme. That  comes with the auctex preview package.
See [that answer on TeX.SE](https://tex.stackexchange.com/questions/52539/preview-latex-background-color) or the [AucTeX preview doc](https://www.gnu.org/software/auctex/manual/preview-latex.html).

**Comment by vuquangtam** [comment]
> 
> 
> The color (foreground and background) of equations should automatically be adapted to the theme. That comes with the auctex preview package.
> See [that answer on TeX.SE](https://tex.stackexchange.com/questions/52539/preview-latex-background-color) or the [AucTeX preview doc](https://www.gnu.org/software/auctex/manual/preview-latex.html).

I got it, thank so much <3

**Comment by jdhao** [comment]
Thanks for the linked post. I figured out how to do it inside `init.el`:

```
(with-eval-after-load 'preview
  ;; we need to change this face, so that image is not shown in black,
  ;; see also https://tex.stackexchange.com/a/52584/114857.
  (set-face-attribute 'preview-reference-face nil
                      :background "NavajoWhite1"))
```
