### ISSUE TITLE
Fragments are not visible over a dark background

### ISSUE THREAD

**Issue by gdindi** [TobiasZawada/texfrag#20]
Hi,
It seems that fragments in png are generated with black foreground over transparent backgound, which makes them invisible if emacs uses a theme with a dark background. Is there a way to configure the package so that it works with a dark background?
Thanks!

**Comment by TobiasZawada** [comment]
Could you post your solution? Did #19 help?

**Comment by gdindi** [comment]
Yes. Sorry for the noise. I found #19 just after posting my issue.
